<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdmissionShsScoreTransmutation extends Seeder
{
    public function run()
    {
        $shsscoretransmutation = [
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 50.00, 'equivalent' => 100.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 49.00, 'equivalent' => 99.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 48.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 47.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 46.00, 'equivalent' => 97.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 45.00, 'equivalent' => 96.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 44.00, 'equivalent' => 95.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 43.00, 'equivalent' => 94.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 42.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 41.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 40.00, 'equivalent' => 92.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 39.00, 'equivalent' => 91.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 38.00, 'equivalent' => 90.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 37.00, 'equivalent' => 89.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 36.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 35.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 34.00, 'equivalent' => 87.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 33.00, 'equivalent' => 86.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 32.00, 'equivalent' => 85.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 31.00, 'equivalent' => 84.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 30.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 29.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 28.00, 'equivalent' => 82.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 27.00, 'equivalent' => 81.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 26.00, 'equivalent' => 80.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 25.00, 'equivalent' => 79.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 24.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 23.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 22.00, 'equivalent' => 77.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 21.00, 'equivalent' => 76.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 20.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 19.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 18.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 17.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 16.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 15.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 14.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 13.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 12.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 11.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 10.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 9.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 8.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 7.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 6.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 5.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 4.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 3.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 2.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 1.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 1, 'subtest_group_id' => 1, 'subtest_name' => 'English', 'rawscore' => 0.00, 'equivalent' => 65.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 50.00, 'equivalent' => 100.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 49.00, 'equivalent' => 99.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 48.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 47.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 46.00, 'equivalent' => 97.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 45.00, 'equivalent' => 96.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 44.00, 'equivalent' => 95.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 43.00, 'equivalent' => 94.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 42.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 41.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 40.00, 'equivalent' => 92.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 39.00, 'equivalent' => 91.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 38.00, 'equivalent' => 90.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 37.00, 'equivalent' => 89.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 36.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 35.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 34.00, 'equivalent' => 87.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 33.00, 'equivalent' => 86.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 32.00, 'equivalent' => 85.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 31.00, 'equivalent' => 84.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 30.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 29.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 28.00, 'equivalent' => 82.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 27.00, 'equivalent' => 81.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 26.00, 'equivalent' => 80.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 25.00, 'equivalent' => 79.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 24.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 23.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 22.00, 'equivalent' => 77.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 21.00, 'equivalent' => 76.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 20.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 19.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 18.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 17.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 16.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 15.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 14.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 13.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 12.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 11.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 10.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 9.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 8.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 7.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 6.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 5.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 4.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 3.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 2.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 1.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 2, 'subtest_group_id' => 1, 'subtest_name' => 'Mathematics', 'rawscore' => 0.00, 'equivalent' => 65.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 50.00, 'equivalent' => 100.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 49.00, 'equivalent' => 99.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 48.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 47.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 46.00, 'equivalent' => 97.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 45.00, 'equivalent' => 96.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 44.00, 'equivalent' => 95.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 43.00, 'equivalent' => 94.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 42.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 41.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 40.00, 'equivalent' => 92.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 39.00, 'equivalent' => 91.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 38.00, 'equivalent' => 90.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 37.00, 'equivalent' => 89.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 36.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 35.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 34.00, 'equivalent' => 87.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 33.00, 'equivalent' => 86.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 32.00, 'equivalent' => 85.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 31.00, 'equivalent' => 84.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 30.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 29.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 28.00, 'equivalent' => 82.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 27.00, 'equivalent' => 81.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 26.00, 'equivalent' => 80.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 25.00, 'equivalent' => 79.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 24.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 23.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 22.00, 'equivalent' => 77.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 21.00, 'equivalent' => 76.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 20.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 19.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 18.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 17.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 16.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 15.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 14.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 13.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 12.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 11.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 10.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 9.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 8.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 7.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 6.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 5.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 4.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 3.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 2.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 1.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 3, 'subtest_group_id' => 1, 'subtest_name' => 'Science', 'rawscore' => 0.00, 'equivalent' => 65.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 100.00, 'equivalent' => 100.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 99.00, 'equivalent' => 99.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 98.00, 'equivalent' => 98.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 97.00, 'equivalent' => 97.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 96.00, 'equivalent' => 96.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 95.00, 'equivalent' => 95.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 94.00, 'equivalent' => 94.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 93.00, 'equivalent' => 93.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 92.00, 'equivalent' => 92.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 91.00, 'equivalent' => 91.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 90.00, 'equivalent' => 90.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 89.00, 'equivalent' => 89.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 88.00, 'equivalent' => 88.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 87.00, 'equivalent' => 87.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 86.00, 'equivalent' => 86.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 85.00, 'equivalent' => 85.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 84.00, 'equivalent' => 84.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 83.00, 'equivalent' => 83.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 82.00, 'equivalent' => 82.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 81.00, 'equivalent' => 81.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 80.00, 'equivalent' => 80.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 79.00, 'equivalent' => 79.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 78.00, 'equivalent' => 78.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 77.00, 'equivalent' => 77.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 76.00, 'equivalent' => 76.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 75.00, 'equivalent' => 75.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 74.00, 'equivalent' => 74.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 73.00, 'equivalent' => 73.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 72.00, 'equivalent' => 72.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 71.00, 'equivalent' => 71.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 70.00, 'equivalent' => 70.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 69.00, 'equivalent' => 69.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 68.00, 'equivalent' => 68.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 67.00, 'equivalent' => 67.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 66.00, 'equivalent' => 66.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 65.00, 'equivalent' => 65.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 64.00, 'equivalent' => 64.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 63.00, 'equivalent' => 63.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 62.00, 'equivalent' => 62.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 61.00, 'equivalent' => 61.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 60.00, 'equivalent' => 60.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 59.00, 'equivalent' => 59.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 58.00, 'equivalent' => 58.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 57.00, 'equivalent' => 57.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 56.00, 'equivalent' => 56.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 55.00, 'equivalent' => 55.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 54.00, 'equivalent' => 54.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 53.00, 'equivalent' => 53.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 52.00, 'equivalent' => 52.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 51.00, 'equivalent' => 51.00, 'created_at' => now(), 'updated_at' => now(),],
            ['subtest_id' => 4, 'subtest_group_id' => 2, 'subtest_name' => 'Arts and Design Rating', 'rawscore' => 50.00, 'equivalent' => 50.00, 'created_at' => now(), 'updated_at' => now(),],
        ];

        DB::table('admission_shs_score_transmutation')->insert($shsscoretransmutation);
    }
}