<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdmissionPseElemG1Rating extends Seeder
{
    public function run()
    {
        $data = [
            ['subtest_id' => 1, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 5, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 6, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 7, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 8, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 9, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 10, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 11, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 12, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 13, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 14, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 15, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 1, 'score' => 16, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 2, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 5, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 6, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 7, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 8, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 9, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 10, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 11, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 12, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 13, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 14, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 15, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 16, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 17, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 2, 'score' => 18, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 3, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 5, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 6, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 7, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 8, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 9, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 10, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 11, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 12, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 13, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 14, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 3, 'score' => 15, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 4, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 5, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 6, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 7, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 8, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 9, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 10, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 11, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 12, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 13, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 14, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 15, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 4, 'score' => 16, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 5, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 5, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 6, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 7, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 8, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 9, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 10, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 11, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 5, 'score' => 12, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 6, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 1, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 2, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 3, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 4, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 5, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 6, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 7, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 8, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 9, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 10, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 11, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 12, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 13, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 14, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 15, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 16, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 17, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 18, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 19, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 20, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 21, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 22, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 23, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 6, 'score' => 24, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['subtest_id' => 7, 'score' => 0, 'rating' => 'Low', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 1, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 2, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 3, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 4, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 5, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 6, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 7, 'rating' => 'Marginal', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 8, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 9, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 10, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 11, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 12, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 13, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 14, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 15, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 16, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 17, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 18, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 19, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 20, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 21, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 22, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 23, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 24, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['subtest_id' => 7, 'score' => 25, 'rating' => 'Adequate', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('admission_pse_subtest_g1_rating')->insert($data);
    }
}
