<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AdmissionJhsScoreTransmutation extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 80.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 79.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 77.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 76.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 75.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 74.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 73.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 72.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 71.00, 'equivalent' => 150.00, 'diq' => '150+', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 70.00, 'equivalent' => 150.00, 'diq' => '150', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 69.00, 'equivalent' => 146.00, 'diq' => '146', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 68.00, 'equivalent' => 142.00, 'diq' => '142', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 67.00, 'equivalent' => 138.00, 'diq' => '138', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 66.00, 'equivalent' => 135.00, 'diq' => '135', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 65.00, 'equivalent' => 133.00, 'diq' => '133', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 64.00, 'equivalent' => 131.00, 'diq' => '131', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 63.00, 'equivalent' => 129.00, 'diq' => '129', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 62.00, 'equivalent' => 127.00, 'diq' => '127', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 61.00, 'equivalent' => 125.00, 'diq' => '125', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 60.00, 'equivalent' => 123.00, 'diq' => '123', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 59.00, 'equivalent' => 122.00, 'diq' => '122', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 58.00, 'equivalent' => 121.00, 'diq' => '121', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 57.00, 'equivalent' => 120.00, 'diq' => '120', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 56.00, 'equivalent' => 119.00, 'diq' => '119', 'description' => 'Superior', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 55.00, 'equivalent' => 118.00, 'diq' => '118', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 54.00, 'equivalent' => 117.00, 'diq' => '117', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 53.00, 'equivalent' => 116.00, 'diq' => '116', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 52.00, 'equivalent' => 115.00, 'diq' => '115', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 51.00, 'equivalent' => 114.00, 'diq' => '114', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 50.00, 'equivalent' => 112.00, 'diq' => '112', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 49.00, 'equivalent' => 112.00, 'diq' => '112', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 48.00, 'equivalent' => 110.00, 'diq' => '110', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 47.00, 'equivalent' => 109.00, 'diq' => '109', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 46.00, 'equivalent' => 109.00, 'diq' => '109', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 45.00, 'equivalent' => 106.00, 'diq' => '106', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 44.00, 'equivalent' => 105.00, 'diq' => '105', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 43.00, 'equivalent' => 104.00, 'diq' => '104', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 42.00, 'equivalent' => 103.00, 'diq' => '103', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 41.00, 'equivalent' => 101.00, 'diq' => '101', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 40.00, 'equivalent' => 100.00, 'diq' => '100', 'description' => 'Above Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 39.00, 'equivalent' => 99.00, 'diq' => '99', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 38.00, 'equivalent' => 98.00, 'diq' => '98', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 37.00, 'equivalent' => 97.00, 'diq' => '97', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 36.00, 'equivalent' => 96.00, 'diq' => '96', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 35.00, 'equivalent' => 94.00, 'diq' => '94', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 34.00, 'equivalent' => 93.00, 'diq' => '93', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 33.00, 'equivalent' => 92.00, 'diq' => '92', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 32.00, 'equivalent' => 91.00, 'diq' => '91', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 31.00, 'equivalent' => 90.00, 'diq' => '90', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 30.00, 'equivalent' => 88.00, 'diq' => '88', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 29.00, 'equivalent' => 87.00, 'diq' => '87', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 28.00, 'equivalent' => 86.00, 'diq' => '86', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 27.00, 'equivalent' => 85.00, 'diq' => '85', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 26.00, 'equivalent' => 84.00, 'diq' => '84', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 25.00, 'equivalent' => 82.00, 'diq' => '82', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 24.00, 'equivalent' => 81.00, 'diq' => '81', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 23.00, 'equivalent' => 80.00, 'diq' => '80', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 22.00, 'equivalent' => 78.00, 'diq' => '78', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 21.00, 'equivalent' => 77.00, 'diq' => '77', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 20.00, 'equivalent' => 76.00, 'diq' => '76', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 19.00, 'equivalent' => 75.00, 'diq' => '75', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 18.00, 'equivalent' => 74.00, 'diq' => '74', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 17.00, 'equivalent' => 73.00, 'diq' => '73', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 16.00, 'equivalent' => 71.00, 'diq' => '71', 'description' => 'Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 15.00, 'equivalent' => 69.00, 'diq' => '69', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 14.00, 'equivalent' => 68.00, 'diq' => '68', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 13.00, 'equivalent' => 66.00, 'diq' => '66', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 12.00, 'equivalent' => 64.00, 'diq' => '64', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 11.00, 'equivalent' => 62.00, 'diq' => '62', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 10.00, 'equivalent' => 60.00, 'diq' => '60', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 9.00, 'equivalent' => 58.00, 'diq' => '58', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 8.00, 'equivalent' => 55.00, 'diq' => '55', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 7.00, 'equivalent' => 53.00, 'diq' => '53', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 6.00, 'equivalent' => 51.00, 'diq' => '51', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 5.00, 'equivalent' => 51.00, 'diq' => '51', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 3.00, 'equivalent' => 50.00, 'diq' => '50', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 2.00, 'equivalent' => 50.00, 'diq' => '50', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 4, 'subtest_name' => 'IQ TEST', 'rawscore' => 1.00, 'equivalent' => 50.00, 'diq' => '50', 'description' => 'Below Average', 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 50.00, 'equivalent' => 100.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 49.00, 'equivalent' => 99.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 48.00, 'equivalent' => 98.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 47.00, 'equivalent' => 96.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 46.00, 'equivalent' => 95.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 45.00, 'equivalent' => 94.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 44.00, 'equivalent' => 93.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 43.00, 'equivalent' => 91.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 42.00, 'equivalent' => 90.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 41.00, 'equivalent' => 89.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 40.00, 'equivalent' => 88.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 39.00, 'equivalent' => 86.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 38.00, 'equivalent' => 85.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 37.00, 'equivalent' => 84.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 36.00, 'equivalent' => 83.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 35.00, 'equivalent' => 81.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 34.00, 'equivalent' => 80.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 33.00, 'equivalent' => 79.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 32.00, 'equivalent' => 78.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 31.00, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 30.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 29.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 28.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 27.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 26.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 25.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 24.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 23.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 22.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 21.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 20.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 19.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 18.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 17.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 16.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 15.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 14.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 13.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 12.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 11.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 10.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 9.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 8.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 7.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 6.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 5.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 4.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 3.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 2.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 1.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 1, 'subtest_name' => 'ENGLISH', 'rawscore' => 0.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 50.00, 'equivalent' => 100.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 49.00, 'equivalent' => 99.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 48.00, 'equivalent' => 98.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 47.00, 'equivalent' => 96.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 46.00, 'equivalent' => 95.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 45.00, 'equivalent' => 94.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 44.00, 'equivalent' => 93.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 43.00, 'equivalent' => 91.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 42.00, 'equivalent' => 90.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 41.00, 'equivalent' => 89.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 40.00, 'equivalent' => 88.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 39.00, 'equivalent' => 86.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 38.00, 'equivalent' => 85.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 37.00, 'equivalent' => 84.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 36.00, 'equivalent' => 83.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 35.00, 'equivalent' => 81.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 34.00, 'equivalent' => 80.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 33.00, 'equivalent' => 79.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 32.00, 'equivalent' => 78.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 31.00, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 30.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 29.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 28.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 27.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 26.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 25.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 24.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 23.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 22.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 21.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 20.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 19.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 18.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 17.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 16.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 15.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 14.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 13.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 12.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 11.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 10.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 9.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 8.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 7.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 6.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 5.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 4.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 3.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 2.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 1.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 2, 'subtest_name' => 'MATHEMATICS', 'rawscore' => 0.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 50.00, 'equivalent' => 100.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 49.00, 'equivalent' => 99.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 48.00, 'equivalent' => 98.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 47.00, 'equivalent' => 96.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 46.00, 'equivalent' => 95.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 45.00, 'equivalent' => 94.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 44.00, 'equivalent' => 93.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 43.00, 'equivalent' => 91.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 42.00, 'equivalent' => 90.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 41.00, 'equivalent' => 89.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 40.00, 'equivalent' => 88.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 39.00, 'equivalent' => 86.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 38.00, 'equivalent' => 85.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 37.00, 'equivalent' => 84.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 36.00, 'equivalent' => 83.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 35.00, 'equivalent' => 81.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 34.00, 'equivalent' => 80.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 33.00, 'equivalent' => 79.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 32.00, 'equivalent' => 78.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 31.00, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 30.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 29.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 28.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 27.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 26.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 25.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 24.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 23.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 22.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 21.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 20.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 19.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 18.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 17.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 16.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 15.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 14.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 13.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 12.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 11.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 10.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 9.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 8.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 7.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 6.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 5.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 4.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 3.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 2.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 1.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 3, 'subtest_name' => 'SCIENCE', 'rawscore' => 0.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 4.00, 'equivalent' => 98.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.90, 'equivalent' => 97.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.80, 'equivalent' => 96.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.70, 'equivalent' => 95.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.60, 'equivalent' => 94.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.50, 'equivalent' => 93.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.40, 'equivalent' => 92.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.30, 'equivalent' => 91.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.20, 'equivalent' => 90.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.10, 'equivalent' => 89.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 3.00, 'equivalent' => 88.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.90, 'equivalent' => 87.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.80, 'equivalent' => 86.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.70, 'equivalent' => 85.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.60, 'equivalent' => 84.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.50, 'equivalent' => 83.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.40, 'equivalent' => 82.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.30, 'equivalent' => 81.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.20, 'equivalent' => 80.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.10, 'equivalent' => 79.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.90, 'equivalent' => 77.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.80, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.70, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 2.00, 'equivalent' => 78.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.40, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.30, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.20, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.10, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 100.00, 'equivalent' => 100.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 99.00, 'equivalent' => 99.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 98.00, 'equivalent' => 98.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 97.00, 'equivalent' => 97.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 96.00, 'equivalent' => 96.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 95.00, 'equivalent' => 95.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 94.00, 'equivalent' => 94.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 93.00, 'equivalent' => 93.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 92.00, 'equivalent' => 92.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 91.00, 'equivalent' => 91.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 90.00, 'equivalent' => 90.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 89.00, 'equivalent' => 89.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 88.00, 'equivalent' => 88.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 87.00, 'equivalent' => 87.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 86.00, 'equivalent' => 86.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 85.00, 'equivalent' => 85.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 84.00, 'equivalent' => 84.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 83.00, 'equivalent' => 83.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 82.00, 'equivalent' => 82.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 81.00, 'equivalent' => 81.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 80.00, 'equivalent' => 80.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 79.00, 'equivalent' => 79.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 78.00, 'equivalent' => 78.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 77.00, 'equivalent' => 77.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 76.00, 'equivalent' => 76.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 75.00, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 74.00, 'equivalent' => 74.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 73.00, 'equivalent' => 73.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 72.00, 'equivalent' => 72.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 71.00, 'equivalent' => 71.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 70.00, 'equivalent' => 70.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 69.00, 'equivalent' => 69.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 68.00, 'equivalent' => 68.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 67.00, 'equivalent' => 67.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 66.00, 'equivalent' => 66.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 65.00, 'equivalent' => 65.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 64.00, 'equivalent' => 64.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 63.00, 'equivalent' => 63.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 62.00, 'equivalent' => 62.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 61.00, 'equivalent' => 61.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 60.00, 'equivalent' => 60.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 59.00, 'equivalent' => 59.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 58.00, 'equivalent' => 58.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 57.00, 'equivalent' => 57.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 56.00, 'equivalent' => 56.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 55.00, 'equivalent' => 55.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 54.00, 'equivalent' => 54.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 53.00, 'equivalent' => 53.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 52.00, 'equivalent' => 52.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 51.00, 'equivalent' => 51.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 50.00, 'equivalent' => 50.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 49.00, 'equivalent' => 49.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 48.00, 'equivalent' => 48.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 47.00, 'equivalent' => 47.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 46.00, 'equivalent' => 46.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 45.00, 'equivalent' => 45.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 44.00, 'equivalent' => 44.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 40.00, 'equivalent' => 40.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 39.00, 'equivalent' => 39.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 38.00, 'equivalent' => 38.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 37.00, 'equivalent' => 37.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 36.00, 'equivalent' => 36.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 35.00, 'equivalent' => 35.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 34.00, 'equivalent' => 34.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 33.00, 'equivalent' => 33.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 32.00, 'equivalent' => 32.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 31.00, 'equivalent' => 31.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 30.00, 'equivalent' => 30.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 29.00, 'equivalent' => 29.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 28.00, 'equivalent' => 28.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 27.00, 'equivalent' => 27.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 26.00, 'equivalent' => 26.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 25.00, 'equivalent' => 25.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 24.00, 'equivalent' => 24.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 23.00, 'equivalent' => 23.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 22.00, 'equivalent' => 22.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 21.00, 'equivalent' => 21.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 20.00, 'equivalent' => 20.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 19.00, 'equivalent' => 19.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 18.00, 'equivalent' => 18.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 17.00, 'equivalent' => 17.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 16.00, 'equivalent' => 16.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 15.00, 'equivalent' => 15.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 14.00, 'equivalent' => 14.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 13.00, 'equivalent' => 13.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 12.00, 'equivalent' => 12.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 11.00, 'equivalent' => 11.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 10.00, 'equivalent' => 10.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 9.00, 'equivalent' => 9.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 8.00, 'equivalent' => 8.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 7.00, 'equivalent' => 7.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 6.00, 'equivalent' => 6.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 5.00, 'equivalent' => 5.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 4.00, 'equivalent' => 4.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 3.00, 'equivalent' => 3.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 2.00, 'equivalent' => 2.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 1.00, 'equivalent' => 1.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 5, 'subtest_name' => 'AUDITION', 'rawscore' => 0.00, 'equivalent' => 0.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 0.00, 'equivalent' => 0.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.60, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['group_id' => 1, 'subtest_id' => 6, 'subtest_name' => 'INTERVIEW', 'rawscore' => 1.50, 'equivalent' => 75.00, 'diq' => NULL, 'description' => NULL, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('admission_jhs_score_transmutation')->insert($data);
    }
}