<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SrmPrograms extends Seeder
{
    public function run()
    {
        $programs = [
            ['code' => 'BSCS', 'name' => 'Bachelor of Science in Computer Science', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Pre-school', 'name' => 'Pre-school Program', 'department_id' => 4, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'SHS', 'name' => 'Science High School', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'SPA', 'name' => 'Special Program for the Arts', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Elementary', 'name' => 'Elementary Program', 'department_id' => 4, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BFA', 'name' => 'Bachelor of Fine Arts (Visual Communication)', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCE', 'name' => 'Bachelor of Science in Civil Engineering', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BS-ECE', 'name' => 'Bachelor of Science in Electronics Engineering', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSIE', 'name' => 'Bachelor of Science in Industrial Engineering', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCPE', 'name' => 'Bachelor of Science in Computer Engineering', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSA', 'name' => 'Bachelor of Science in Accountancy', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSHM', 'name' => 'Bachelor of Science in Hospitality Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSTM', 'name' => 'Bachelor of Science in Tourism Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABCOMM', 'name' => 'Bachelor of Arts in Communication', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABENGLISH', 'name' => 'Bachelor of Arts in English Language', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCHEM', 'name' => 'Bachelor of Science in Chemistry', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSPSYCH', 'name' => 'Bachelor of Science in Psychology', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BLIS', 'name' => 'Bachelor of Library and Information Science', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BEED', 'name' => 'Bachelor of Elementary Education', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSED-MATH', 'name' => 'Bachelor of Secondary Education Major in Mathematics', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABPHILO', 'name' => 'Bachelor of Arts in Philosophy', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABPOLSCI', 'name' => 'Bachelor of Arts in Political Science', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-FM', 'name' => 'Bachelor of Science in Business Administration Major in Financial Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-MM', 'name' => 'Bachelor of Science in Business Administration Major in Marketing Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-HRDM', 'name' => 'Bachelor of Science in Business Administration Major in Human Resource Development Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSMT', 'name' => 'Bachelor of Science in Medical Technology', 'department_id' => 8, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSPH', 'name' => 'Bachelor of Science in Pharmacy', 'department_id' => 8, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSN', 'name' => 'Bachelor of Science in Nursing', 'department_id' => 8, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSNL', 'name' => 'Bachelor of Science in Nursing (Ladderized)', 'department_id' => 8, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSECE', 'name' => 'Bachelor of Science in Electronics and Communication Engineering', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'DBA', 'name' => 'Doctor of Business Administration', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-PA', 'name' => 'Doctor of Philosophy Major in Public Administration', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-DE', 'name' => 'Doctor of Philosophy Major in Development Education', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-RE', 'name' => 'Master of Arts in Education Major in Religious Education', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-EM', 'name' => 'Master of Arts in Education Major in Educational Management', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-GC', 'name' => 'Master of Arts in Education Major in Guidance Counseling', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-MST', 'name' => 'Master of Arts in Education Major in Math and Science Teaching', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAN', 'name' => 'Master of Arts in Nursing', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA', 'name' => 'Master in Business Administration', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MPA Plan B', 'name' => 'Master in Public Administration Major in Local Governance - Plan B', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MSME', 'name' => 'Master of Science in Management Engineering', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'LAW', 'name' => 'Bachelor of Laws', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MLS', 'name' => 'Master in Legal Studies', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSARCHI', 'name' => 'Bachelor of Science in Architecture', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSENTREP', 'name' => 'Bachelor of Science in Entrepreneurship', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSED-ENG', 'name' => 'Bachelor of Secondary Education Major in English', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BEED-ECD', 'name' => 'Bachelor of Elementary Education Major in Early Childhood and Development', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA Plan B', 'name' => 'Master in Business Administration (Plan B - Non-Thesis Executive Program for Clergy)', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-CE', 'name' => 'Doctor of Philosophy Major in Counselor Education', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HS-GC', 'name' => 'High School General Curriculum', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABJOURN', 'name' => 'Bachelor of Arts in Journalism', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABLIT', 'name' => 'Bachelor of Arts in Literature', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA', 'name' => 'Bachelor of Science in Business Administration', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSOA', 'name' => 'Bachelor of Science in Office Administration', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSED-GS', 'name' => 'Bachelor of Science in Secondary Education Major in  General Science', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'LAW-Rf', 'name' => 'Bachelor of Laws - Refresher', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD', 'name' => 'Doctor of Philosophy', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MA', 'name' => 'Master of Arts', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'LAW-SitIn', 'name' => 'Bachelor of Laws - SitIn', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'GAS', 'name' => 'General Academic Strand', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HumSS', 'name' => 'Humanities & Social Sciences', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABM', 'name' => 'Accountancy, Business & Management', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'STEM', 'name' => 'Science, Technology, Engineering & Mathematics', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'STEM+', 'name' => 'Science, Technology, Engineering & Mathematics Plus', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HE Cookery', 'name' => 'Home Economics: Cookery', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HE Bread and Pastry Production', 'name' => 'Home Economics: Bread and Pastry Production', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HE Food and Beverage Services', 'name' => 'Home Economics: Food and Beverage Services', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'HE Housekeeping', 'name' => 'Home Economics: Housekeeping', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'IA Plumbing', 'name' => 'Industrial Art: Plumbing', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ICT Technical Drafting', 'name' => 'Information and Communication Technology: Technical Drafting', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ICT Pharmacy Aid', 'name' => 'Information and Communication Technology: Pharmacy Aid', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ICT AMSM', 'name' => 'Information and Communication Technology: Accounting and Marketing Services Management', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Performing Arts', 'name' => 'Performing Arts', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Sports', 'name' => 'Sports', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Arts Production', 'name' => 'Arts Production', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED', 'name' => 'Master of Arts in Education', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ABECON', 'name' => 'Bachelor of Arts in Economics', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Law-Rf-UNC', 'name' => 'Law - Refresher - UNC', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'CPT', 'name' => 'Certificate in Professional Teaching', 'department_id' => 35, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-FM*', 'name' => 'Bachelor of Science in Business Administration Major in Financial Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-MM*', 'name' => 'Bachelor of Science in Business Administration Major in Marketing Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-HRDM*', 'name' => 'Bachelor of Science in Business Administration Major in Human Resource Development Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSENTREP*', 'name' => 'Bachelor of Science in Entrepreneurship with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSTM*', 'name' => 'Bachelor of Science in Tourism Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSHM*', 'name' => 'Bachelor of Science in Hospitality Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSA*', 'name' => 'Bachelor of Science in Accountancy *', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCE*', 'name' => 'Bachelor of Science in Civil Engineering with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSIE*', 'name' => 'Bachelor of Science in Industrial Engineering with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCPE*', 'name' => 'Bachelor of Science in Computer Engineering with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSECE*', 'name' => 'Bachelor of Science in Electronics Engineering with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSARCHI*', 'name' => 'Bachelor of Science in Architecture with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSCS*', 'name' => 'Bachelor of Science in Computer Science with Bridge Courses', 'department_id' => 9, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'LAW PreBar', 'name' => 'Bachelor of Laws - PreBar', 'department_id' => 10, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'ML', 'name' => 'Master of Laws (DHEI : University of Santo Tomas - Manila)', 'department_id' => 40, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PSE Languages', 'name' => 'PSE Languages', 'department_id' => 4, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PSE Makabayan', 'name' => 'PSE Makabayan', 'department_id' => 4, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'JHS Science and Technology', 'name' => 'JHS Science and Technology', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PSE Science and Math', 'name' => 'PSE Science and Math', 'department_id' => 4, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'JHS SPA', 'name' => 'JHS SPA', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'JHS Mathematics', 'name' => 'JHS Mathematics', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'JHS Languages', 'name' => 'JHS Languages', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'JHS Social Studies', 'name' => 'JHS Social Studies', 'department_id' => 5, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Humanities', 'name' => 'Humanities', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PE', 'name' => 'PE', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Languages', 'name' => 'Languages', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Social Sciences', 'name' => 'Social Sciences', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Math and Science', 'name' => 'Math and Science', 'department_id' => 6, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BST-HRM', 'name' => 'Bachelor of Science in Tourism Major in Hotel and Restaurant Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'CREED', 'name' => 'Center for Religious Education', 'department_id' => 1, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'NSTP', 'name' => 'National Service Training Program', 'department_id' => 3, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Guidance Program', 'name' => 'Guidance Program', 'department_id' => 14, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'SHS Languages', 'name' => 'SHS Languages', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-HRM', 'name' => 'Bachelor of Science in Business Administration Major in Human Resource Management', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'STEM INT', 'name' => 'Science, Technology, Engineering and Mathematics - Internal', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'STEM EXT', 'name' => 'Science, Technology, Engineering and Mathematics - External', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'Arts and Design', 'name' => 'Arts and Design', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'STEM A', 'name' => 'Science, Technology, Engineering and Mathematics A', 'department_id' => 31, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'BSBA-HRM*', 'name' => 'Bachelor of Science in Business Administration Major in Human Resource Management with Bridge Courses', 'department_id' => 7, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MPA PLAN A', 'name' => 'Master in Public Administration major in Local Governance - Plan A ', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA Plan A', 'name' => 'Master in Business Administration -Plan A', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA -Plan B', 'name' => 'Master in Business Administration -Plan B', 'department_id' => 11, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'DBA', 'name' => 'Doctor of Business Administration', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-PA', 'name' => 'Doctor of Philosophy Major in Public Administration', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-DE', 'name' => 'Doctor of Philosophy Major in Development Education', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-RE', 'name' => 'Master of Arts in Education Major in Religious Education', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-EM', 'name' => 'Master of Arts in Education Major in Educational Management', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-GC', 'name' => 'Master of Arts in Education Major in Guidance Counseling', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED-MST', 'name' => 'Master of Arts in Education Major in Math and Science Teaching', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAN', 'name' => 'Master of Arts in Nursing', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA', 'name' => 'Master in Business Administration', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MPA Plan B', 'name' => 'Master in Public Administration Major in Local Governance - Plan B', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MSME', 'name' => 'Master of Science in Management Engineering', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA Plan B', 'name' => 'Master in Business Administration (Plan B - Non-Thesis Executive Program for Clergy)', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD-CE', 'name' => 'Doctor of Philosophy Major in Counselor Education', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'PHD', 'name' => 'Doctor of Philosophy', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MA', 'name' => 'Master of Arts', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MAED', 'name' => 'Master of Arts in Education', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MPA PLAN A', 'name' => 'Master in Public Administration major in Local Governance - Plan A ', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA Plan A', 'name' => 'Master in Business Administration -Plan A', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['code' => 'MBA -Plan B', 'name' => 'Master in Business Administration -Plan B', 'department_id' => 44, 'is_active' => 1, 'created_at' => now(), 'updated_at' => now(),],
        ];

        foreach ($programs as &$program) {
            $program['api'] = 0;
            $program['prereq'] = null;
        }

        DB::table('srm_programs')->insert($programs);
    }
}