<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SysAddressTownsSeeder extends Seeder
{
    public function run()
    {
        $towns = [
            ['name' => 'Bacacay', 'province_id' => 5],
            ['name' => 'Camalig', 'province_id' => 5],
            ['name' => 'Daraga', 'province_id' => 5],
            ['name' => 'Guinobatan', 'province_id' => 5],
            ['name' => 'Jovellar', 'province_id' => 5],
            ['name' => 'Legazpi City', 'province_id' => 5],
            ['name' => 'Libon', 'province_id' => 5],
            ['name' => 'Ligao City', 'province_id' => 5],
            ['name' => 'Malilipot', 'province_id' => 5],
            ['name' => 'Malinao', 'province_id' => 5],
            ['name' => 'Manito', 'province_id' => 5],
            ['name' => 'Oas', 'province_id' => 5],
            ['name' => 'Pio Duran', 'province_id' => 5],
            ['name' => 'Polangui', 'province_id' => 5],
            ['name' => 'Rapu-Rapu', 'province_id' => 5],
            ['name' => 'Sto. Domingo', 'province_id' => 5],
            ['name' => 'Tabaco City', 'province_id' => 5],
            ['name' => 'Tiwi', 'province_id' => 5],

            ['name' => 'Villaviciosa', 'province_id' => 1],
            ['name' => 'Tubo', 'province_id' => 1],
            ['name' => 'Tineg', 'province_id' => 1],
            ['name' => 'Tayum', 'province_id' => 1],
            ['name' => 'San Quintin', 'province_id' => 1],
            ['name' => 'San Juan', 'province_id' => 1],
            ['name' => 'San Isidro', 'province_id' => 1],
            ['name' => 'Sallapadan', 'province_id' => 1],
            ['name' => 'Pilar', 'province_id' => 1],
            ['name' => 'Pidigan', 'province_id' => 1],
            ['name' => 'Pe', 'province_id' => 1],
            ['name' => 'Manabo', 'province_id' => 1],
            ['name' => 'Malibcong', 'province_id' => 1],
            ['name' => 'Luba', 'province_id' => 1],
            ['name' => 'Licuan-Baay', 'province_id' => 1],
            ['name' => 'Langiden', 'province_id' => 1],
            ['name' => 'Lagayan', 'province_id' => 1],
            ['name' => 'Lagangilang', 'province_id' => 1],
            ['name' => 'Lacub', 'province_id' => 1],
            ['name' => 'La Paz', 'province_id' => 1],
            ['name' => 'Dolores', 'province_id' => 1],
            ['name' => 'Danglas', 'province_id' => 1],
            ['name' => 'Daguioman', 'province_id' => 1],
            ['name' => 'Bucloc', 'province_id' => 1],
            ['name' => 'Bucay', 'province_id' => 1],
            ['name' => 'Boliney', 'province_id' => 1],
            ['name' => 'Bangued', 'province_id' => 1],

            ['name' => 'Angat', 'province_id' => 17],
            ['name' => 'Balagtas (Bigaa)', 'province_id' => 17],
            ['name' => 'Baliuag', 'province_id' => 17],
            ['name' => 'Bocaue', 'province_id' => 17],
            ['name' => 'Bulacan or Bulakan', 'province_id' => 17],
            ['name' => 'Bustos', 'province_id' => 17],
            ['name' => 'Calumpit', 'province_id' => 17],
            ['name' => 'Do', 'province_id' => 17],
            ['name' => 'Guiguinto', 'province_id' => 17],
            ['name' => 'Hagonoy', 'province_id' => 17],
            ['name' => 'Malolos City', 'province_id' => 17],
            ['name' => 'Marilao', 'province_id' => 17],
            ['name' => 'Meycauayan City', 'province_id' => 17],
            ['name' => 'Norzagaray', 'province_id' => 17],
            ['name' => 'Obando', 'province_id' => 17],
            ['name' => 'Pandi', 'province_id' => 17],
            ['name' => 'Paombong', 'province_id' => 17],
            ['name' => 'Plaridel', 'province_id' => 17],
            ['name' => 'Pulilan', 'province_id' => 17],
            ['name' => 'San Ildefonso', 'province_id' => 17],
            ['name' => 'San Jose del Monte City', 'province_id' => 17],
            ['name' => 'San Miguel', 'province_id' => 17],
            ['name' => 'San Rafael', 'province_id' => 17],
            ['name' => 'Santa Maria', 'province_id' => 17],

            ['name' => 'Abulug', 'province_id' => 18],
            ['name' => 'Alcala', 'province_id' => 18],
            ['name' => 'Allacapan', 'province_id' => 18],
            ['name' => 'Amulung', 'province_id' => 18],
            ['name' => 'Aparri', 'province_id' => 18],
            ['name' => 'Baggao', 'province_id' => 18],
            ['name' => 'Ballesteros', 'province_id' => 18],
            ['name' => 'Buguey', 'province_id' => 18],
            ['name' => 'Calayan', 'province_id' => 18],
            ['name' => 'Camalaniugan', 'province_id' => 18],
            ['name' => 'Claveria', 'province_id' => 18],
            ['name' => 'Enrile', 'province_id' => 18],
            ['name' => 'Gattaran', 'province_id' => 18],
            ['name' => 'Gonzaga', 'province_id' => 18],
            ['name' => 'Tuguegarao City', 'province_id' => 18],
            ['name' => 'Iguig', 'province_id' => 18],
            ['name' => 'Lal-Lo', 'province_id' => 18],
            ['name' => 'Lasam', 'province_id' => 18],
            ['name' => 'Pamplona', 'province_id' => 18],
            ['name' => 'Pe', 'province_id' => 18],
            ['name' => 'Piat', 'province_id' => 18],
            ['name' => 'Rizal', 'province_id' => 18],
            ['name' => 'Sanchez-Mira', 'province_id' => 18],
            ['name' => 'Santa Ana', 'province_id' => 18],
            ['name' => 'Santa Praxedes', 'province_id' => 18],
            ['name' => 'Santa Teresita', 'province_id' => 18],
            ['name' => 'Santo Ni', 'province_id' => 18],
            ['name' => 'Solana', 'province_id' => 18],
            ['name' => 'Tuao', 'province_id' => 18],

            ['name' => 'Basud', 'province_id' => 19],
            ['name' => 'Capalonga', 'province_id' => 19],
            ['name' => 'Daet', 'province_id' => 19],
            ['name' => 'Jose Panganiban', 'province_id' => 19],
            ['name' => 'Labo', 'province_id' => 19],
            ['name' => 'Mercedes', 'province_id' => 19],
            ['name' => 'Paracale', 'province_id' => 19],
            ['name' => 'San Lorenzo Ruiz', 'province_id' => 19],
            ['name' => 'San Vicente', 'province_id' => 19],
            ['name' => 'Santa Elena', 'province_id' => 19],
            ['name' => 'Talisay', 'province_id' => 19],
            ['name' => 'Vinzons', 'province_id' => 19],

            ['name' => 'Baao', 'province_id' => 20],
            ['name' => 'Balatan', 'province_id' => 20],
            ['name' => 'Bato', 'province_id' => 20],
            ['name' => 'Bombon', 'province_id' => 20],
            ['name' => 'Buhi', 'province_id' => 20],
            ['name' => 'Bula', 'province_id' => 20],
            ['name' => 'Cabusao', 'province_id' => 20],
            ['name' => 'Calabanga', 'province_id' => 20],
            ['name' => 'Camaligan', 'province_id' => 20],
            ['name' => 'Canaman', 'province_id' => 20],
            ['name' => 'Caramoan', 'province_id' => 20],
            ['name' => 'Del Gallego', 'province_id' => 20],
            ['name' => 'Gainza', 'province_id' => 20],
            ['name' => 'Garchitorena', 'province_id' => 20],
            ['name' => 'Goa', 'province_id' => 20],
            ['name' => 'Iriga City', 'province_id' => 20],
            ['name' => 'Lagonoy', 'province_id' => 20],
            ['name' => 'Libmanan', 'province_id' => 20],
            ['name' => 'Lupi', 'province_id' => 20],
            ['name' => 'Magarao', 'province_id' => 20],
            ['name' => 'Milaor', 'province_id' => 20],
            ['name' => 'Minalabac', 'province_id' => 20],
            ['name' => 'Nabua', 'province_id' => 20],
            ['name' => 'Naga City', 'province_id' => 20],
            ['name' => 'Ocampo', 'province_id' => 20],
            ['name' => 'Pamplona', 'province_id' => 20],
            ['name' => 'Pasacao', 'province_id' => 20],
            ['name' => 'Pili', 'province_id' => 20],
            ['name' => 'Presentacion', 'province_id' => 20],
            ['name' => 'Ragay', 'province_id' => 20],
            ['name' => 'San Fernando', 'province_id' => 20],
            ['name' => 'San Jose', 'province_id' => 20],
            ['name' => 'Sipocot', 'province_id' => 20],
            ['name' => 'Siruma', 'province_id' => 20],
            ['name' => 'Tigaon', 'province_id' => 20],
            ['name' => 'Tinambac', 'province_id' => 20],

            ['name' => 'Bagamanoc', 'province_id' => 23],
            ['name' => 'Baras', 'province_id' => 23],
            ['name' => 'Bato', 'province_id' => 23],
            ['name' => 'Caramoran', 'province_id' => 23],
            ['name' => 'Gigmoto', 'province_id' => 23],
            ['name' => 'Pandan', 'province_id' => 23],
            ['name' => 'Panganiban (Payo)', 'province_id' => 23],
            ['name' => 'San Andres (Calolbon)', 'province_id' => 23],
            ['name' => 'San Miguel', 'province_id' => 23],
            ['name' => 'Viga', 'province_id' => 23],
            ['name' => 'Virac', 'province_id' => 23],

            ['name' => 'Alfonso', 'province_id' => 24],
            ['name' => 'Amadeo', 'province_id' => 24],
            ['name' => 'Bacoor', 'province_id' => 24],
            ['name' => 'Carmona', 'province_id' => 24],
            ['name' => 'Gen. Emilio Aguinaldo', 'province_id' => 24],
            ['name' => 'Gen. Mariano Alvarez', 'province_id' => 24],
            ['name' => 'General Trias', 'province_id' => 24],
            ['name' => 'Imus', 'province_id' => 24],
            ['name' => 'Indang', 'province_id' => 24],
            ['name' => 'Kawit', 'province_id' => 24],
            ['name' => 'Magallanes', 'province_id' => 24],
            ['name' => 'Maragondon', 'province_id' => 24],
            ['name' => 'Mendez', 'province_id' => 24],
            ['name' => 'Naic', 'province_id' => 24],
            ['name' => 'Noveleta', 'province_id' => 24],
            ['name' => 'Rosario', 'province_id' => 24],
            ['name' => 'Silang', 'province_id' => 24],
            ['name' => 'Tanza', 'province_id' => 24],
            ['name' => 'Ternate', 'province_id' => 24],

            ['name' => 'Alaminos', 'province_id' => 41],
            ['name' => 'Bay', 'province_id' => 41],
            ['name' => 'Cabuyao', 'province_id' => 41],
            ['name' => 'Calamba City', 'province_id' => 41],
            ['name' => 'Calauan', 'province_id' => 41],
            ['name' => 'Cavinti', 'province_id' => 41],
            ['name' => 'Famy', 'province_id' => 41],
            ['name' => 'Kalayaan', 'province_id' => 41],
            ['name' => 'Liliw', 'province_id' => 41],
            ['name' => 'Luisiana', 'province_id' => 41],
            ['name' => 'Lumban', 'province_id' => 41],
            ['name' => 'Mabitac', 'province_id' => 41],
            ['name' => 'Magdalena', 'province_id' => 41],
            ['name' => 'Majayjay', 'province_id' => 41],
            ['name' => 'Nagcarlan', 'province_id' => 41],
            ['name' => 'Paete', 'province_id' => 41],
            ['name' => 'Pagsanjan', 'province_id' => 41],
            ['name' => 'Pakil', 'province_id' => 41],
            ['name' => 'Pila', 'province_id' => 41],
            ['name' => 'Rizal', 'province_id' => 41],
            ['name' => 'San Pablo City', 'province_id' => 41],
            ['name' => 'San Pedro', 'province_id' => 41],
            ['name' => 'Santa Cruz', 'province_id' => 41],
            ['name' => 'Santa Maria', 'province_id' => 41],
            ['name' => 'Santa Rosa City', 'province_id' => 41],
            ['name' => 'Siniloan', 'province_id' => 41],
            ['name' => 'Victoria', 'province_id' => 41],

            ['name' => 'Caloocan City', 'province_id' => 81],
            ['name' => 'Makati City', 'province_id' => 81],
            ['name' => 'Malabon City', 'province_id' => 81],
            ['name' => 'Mandaluyong City', 'province_id' => 81],
            ['name' => 'Manila', 'province_id' => 81],
            ['name' => 'Marikina City', 'province_id' => 81],
            ['name' => 'Muntinlupa City', 'province_id' => 81],
            ['name' => 'Navotas City', 'province_id' => 81],
            ['name' => 'Pasay City', 'province_id' => 81],
            ['name' => 'Pasig City', 'province_id' => 81],
            ['name' => 'Pateros', 'province_id' => 81],
            ['name' => 'Quezon City', 'province_id' => 81],
            ['name' => 'San Juan City', 'province_id' => 81],
            ['name' => 'Taguig City', 'province_id' => 81],
            ['name' => 'Valenzuela City', 'province_id' => 81],

            ['name' => 'Aroroy', 'province_id' => 47],
            ['name' => 'Baleno', 'province_id' => 47],
            ['name' => 'Balud', 'province_id' => 47],
            ['name' => 'Batuan', 'province_id' => 47],
            ['name' => 'Cataingan', 'province_id' => 47],
            ['name' => 'Cawayan', 'province_id' => 47],
            ['name' => 'Claveria', 'province_id' => 47],
            ['name' => 'Dimasalang', 'province_id' => 47],
            ['name' => 'Esperanza', 'province_id' => 47],
            ['name' => 'Mandaon', 'province_id' => 47],
            ['name' => 'Masbate City', 'province_id' => 47],
            ['name' => 'Milagros', 'province_id' => 47],
            ['name' => 'Mobo', 'province_id' => 47],
            ['name' => 'Monreal', 'province_id' => 47],
            ['name' => 'Palanas', 'province_id' => 47],
            ['name' => 'Pio V. Corpuz', 'province_id' => 47],
            ['name' => 'Placer', 'province_id' => 47],
            ['name' => 'San Fernando', 'province_id' => 47],
            ['name' => 'San Jacinto', 'province_id' => 47],
            ['name' => 'San Pascual', 'province_id' => 47],
            ['name' => 'Uson', 'province_id' => 47],

            ['name' => 'Angeles City', 'province_id' => 59],
            ['name' => 'Apalit', 'province_id' => 59],
            ['name' => 'Arayat', 'province_id' => 59],
            ['name' => 'Bacolor', 'province_id' => 59],
            ['name' => 'Candaba', 'province_id' => 59],
            ['name' => 'City of San Fernando', 'province_id' => 59],
            ['name' => 'Floridablanca', 'province_id' => 59],
            ['name' => 'Guagua', 'province_id' => 59],
            ['name' => 'Lubao', 'province_id' => 59],
            ['name' => 'Mabalacat', 'province_id' => 59],
            ['name' => 'Macabebe', 'province_id' => 59],
            ['name' => 'Magalang', 'province_id' => 59],
            ['name' => 'Masantol', 'province_id' => 59],
            ['name' => 'Mexico', 'province_id' => 59],
            ['name' => 'Minalin', 'province_id' => 59],
            ['name' => 'Porac', 'province_id' => 59],
            ['name' => 'San Luis', 'province_id' => 59],
            ['name' => 'San Simon', 'province_id' => 59],
            ['name' => 'Santa Ana', 'province_id' => 59],
            ['name' => 'Santa Rita', 'province_id' => 59],
            ['name' => 'Santo Tomas', 'province_id' => 59],
            ['name' => 'Sasmuan', 'province_id' => 59],

            ['name' => 'Barcelona', 'province_id' => 68],
            ['name' => 'Bulan', 'province_id' => 68],
            ['name' => 'Bulusan', 'province_id' => 68],
            ['name' => 'Casiguran', 'province_id' => 68],
            ['name' => 'Castilla', 'province_id' => 68],
            ['name' => 'Donsol', 'province_id' => 68],
            ['name' => 'Gubat', 'province_id' => 68],
            ['name' => 'Irosin', 'province_id' => 68],
            ['name' => 'Juban', 'province_id' => 68],
            ['name' => 'Magallanes', 'province_id' => 68],
            ['name' => 'Matnog', 'province_id' => 68],
            ['name' => 'Pilar', 'province_id' => 68],
            ['name' => 'Prieto Diaz', 'province_id' => 68],
            ['name' => 'Santa Magdalena', 'province_id' => 68],
            ['name' => 'Sorsogon City', 'province_id' => 68],

            ['name' => 'Calbayog City', 'province_id' => 65],
            ['name' => 'Catbalogan City', 'province_id' => 65],
            ['name' => 'Almagro', 'province_id' => 65],
            ['name' => 'Basey', 'province_id' => 65],
            ['name' => 'Calbiga', 'province_id' => 65],
            ['name' => 'Daram', 'province_id' => 65],
            ['name' => 'Gandara', 'province_id' => 65],
            ['name' => 'Hinabangan', 'province_id' => 65],
            ['name' => 'Jiabong', 'province_id' => 65],
            ['name' => 'Marabut', 'province_id' => 65],
            ['name' => 'Matuguinao', 'province_id' => 65],
            ['name' => 'Motiong', 'province_id' => 65],
            ['name' => 'Pagsanghan', 'province_id' => 65],
            ['name' => 'Paranas (Wright)', 'province_id' => 65],
            ['name' => 'Pinabacdao', 'province_id' => 65],
            ['name' => 'San Jorge', 'province_id' => 65],
            ['name' => 'San Jose De Buan', 'province_id' => 65],
            ['name' => 'San Sebastian', 'province_id' => 65],
            ['name' => 'Santa Margarita', 'province_id' => 65],
            ['name' => 'Santa Rita', 'province_id' => 65],
            ['name' => 'Tagapul-an', 'province_id' => 65],
            ['name' => 'Talalora', 'province_id' => 65],
            ['name' => 'Tarangnan', 'province_id' => 65],
            ['name' => 'Villareal', 'province_id' => 65],
            ['name' => 'Zumarraga', 'province_id' => 65],

            ['name' => 'Allen', 'province_id' => 53],
            ['name' => 'Biri', 'province_id' => 53],
            ['name' => 'Bobon', 'province_id' => 53],
            ['name' => 'Capul', 'province_id' => 53],
            ['name' => 'Catarman', 'province_id' => 53],
            ['name' => 'Catubig', 'province_id' => 53],
            ['name' => 'Gamay', 'province_id' => 53],
            ['name' => 'Laoang', 'province_id' => 53],
            ['name' => 'Lapinig', 'province_id' => 53],
            ['name' => 'Las Navas', 'province_id' => 53],
            ['name' => 'Lavezares', 'province_id' => 53],
            ['name' => 'Lope de Vega', 'province_id' => 53],
            ['name' => 'Mapanas', 'province_id' => 53],
            ['name' => 'Mondragon', 'province_id' => 53],
            ['name' => 'Palapag', 'province_id' => 53],
            ['name' => 'Pambujan', 'province_id' => 53],
            ['name' => 'Rosario', 'province_id' => 53],
            ['name' => 'San Antonio', 'province_id' => 53],
            ['name' => 'San Jose', 'province_id' => 53],
            ['name' => 'San Roque', 'province_id' => 53],
            ['name' => 'San Vicente', 'province_id' => 53],
            ['name' => 'Silvino Lobos', 'province_id' => 53],
            ['name' => 'Victoria', 'province_id' => 53],

            ['name' => 'Other', 'province_id' => 82],

            ['name' => 'Agdangan', 'province_id' => 61],
            ['name' => 'Alabat', 'province_id' => 61],
            ['name' => 'Atimonan', 'province_id' => 61],
            ['name' => 'Buenavista', 'province_id' => 61],
            ['name' => 'Burdeos', 'province_id' => 61],
            ['name' => 'Calauag', 'province_id' => 61],
            ['name' => 'Candelaria', 'province_id' => 61],
            ['name' => 'Catanauan', 'province_id' => 61],
            ['name' => 'Dolores', 'province_id' => 61],
            ['name' => 'General Luna', 'province_id' => 61],
            ['name' => 'General Nakar', 'province_id' => 61],
            ['name' => 'Guinayangan', 'province_id' => 61],
            ['name' => 'Gumaca', 'province_id' => 61],
            ['name' => 'Infanta', 'province_id' => 61],
            ['name' => 'Jomalig', 'province_id' => 61],
            ['name' => 'Lopez', 'province_id' => 61],
            ['name' => 'Lucban', 'province_id' => 61],
            ['name' => 'Macalelon', 'province_id' => 61],
            ['name' => 'Mauban', 'province_id' => 61],
            ['name' => 'Mulanay', 'province_id' => 61],
            ['name' => 'Padre Burgos', 'province_id' => 61],
            ['name' => 'Pagbilao', 'province_id' => 61],
            ['name' => 'Panukulan', 'province_id' => 61],
            ['name' => 'Patnanungan', 'province_id' => 61],
            ['name' => 'Perez', 'province_id' => 61],
            ['name' => 'Pitogo', 'province_id' => 61],
            ['name' => 'Plaridel', 'province_id' => 61],
            ['name' => 'Polillo', 'province_id' => 61],
            ['name' => 'Quezon', 'province_id' => 61],
            ['name' => 'Real', 'province_id' => 61],
            ['name' => 'Sampaloc', 'province_id' => 61],
            ['name' => 'San Andres', 'province_id' => 61],
            ['name' => 'San Antonio', 'province_id' => 61],
            ['name' => 'San Francisco', 'province_id' => 61],
            ['name' => 'San Narciso', 'province_id' => 61],
            ['name' => 'Sariaya', 'province_id' => 61],
            ['name' => 'Tagkawayan', 'province_id' => 61],
            ['name' => 'Tiaong', 'province_id' => 61],
            ['name' => 'Unisan', 'province_id' => 61],

            ['name' => 'Las Piñas', 'province_id' => 81],
            ['name' => 'Sampaloc', 'province_id' => 81],

            ['name' => 'Ajuy', 'province_id' => 37],
            ['name' => 'Iloilo City', 'province_id' => 37],
        ];

        foreach ($towns as $town) {
            DB::table('sys_address_towns')->insert([
                'name' => $town['name'],
                'province_id' => $town['province_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
